version: '3.8'
services:
  mongo:
    image: mongo
    container_name: dev-api-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER_NAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5