version: '3.8'
services:
  mongo:
    image: mongo
    container_name: dev-api-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=leon
      - MONGO_INITDB_ROOT_PASSWORD=hhamk21750940nz9cxqeeozpk1s5tu
    ports:
      - 27018:27017
    volumes:
      - ./mongo-data:/data/db
    command: --wiredTigerCacheSizeGB 1.5