import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, IsString } from 'class-validator';

export class CaptchaDto {
    @ApiProperty({ type: String, description: 'Value generated by Google reCAPTCHA' })
    @IsNotEmpty()
    @IsString()
    response: string;
}